name: Deploy website
on: [push]
branches:
  - master
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: build and test
      - uses: actions/checkout@master
        run: |
          npm ci
          npm run build

      - name: Upload to S3
      - uses: actions/checkout@master
      - uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
        env:
          FILE: ./build/*
          AWS_REGION: 'eu-north-1'
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}